name: Clojure CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: "17"
    - name: Setup clojure
      uses: DeLaGuardo/setup-clojure@13.0
      with:
        lein: 'latest'
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
