name: Clojure Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: "17"
    - name: Setup clojure
      uses: DeLaGuardo/setup-clojure@13.0
      with:
        lein: 'latest'
    - name: Get version
      id: get_version
      run: |
        VERSION=$(perl -nle 'if (/^## .+?(\d+\.\d+\.\d+)/) { print $1; last }' CHANGELOG.md)
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
    - name: Update project.clj
      run: sed -e 's/{{version}}/${{ steps.get_version.outputs.version }}/' project.clj.template > project.clj
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Create tag
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ steps.get_version.outputs.version }}
    - name: Publish to clojars
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      run: lein deploy clojars
